In [48]:
import pandas as pd 
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import os
import re
import importlib

In [49]:
data_path = os.path.abspath("data/tcga_data2.csv")

raw_df = pd.read_csv(data_path, sep = '\t', low_memory = False)
raw_df.head(1)

,Gene,Study of Origin,Sample ID,Cancer Type,Cancer Type Detailed,Protein Change,Annotation,Custom Driver,Custom Driver Tiers,Functional Impact,...,Tumor Type,Used in Genomic Analysis,Vascular invasion indicator,Vessel Invasion,Vial number,Patient's Vital Status,Patient Weight,WGD,Winter Hypoxia Score,Year of Diagnosis
0,APC,"Colorectal Adenocarcinoma (TCGA, Firehose Legacy)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NO,NaN,A,NaN,NaN,NaN,NaN,NaN

In [50]:
# https://docs.python.org/3/library/re.html
# \b is a space
cols = np.array(raw_df.columns.tolist())
pattern = re.compile(r'\bage\b', flags = re.IGNORECASE)
age_cols = np.array([])

for col in cols:
    # Regex needs pattern.search, instead of say "str".in(array)
    if pattern.search(col) and ("Diagnosis" in col):
        age_cols = np.append(age_cols, col)

age_cols

array(['Diagnosis Age', 'Age at Diagnosis', 'Age At Diagnosis'],
      dtype='<U32')

In [51]:
note_cols = ["Gene", "Sample ID", "Cancer Type Detailed", "Mutation Type", "Variant Type", "HGVSc", "MS", 
        "Protein Change", "Functional Impact"]

good_cols = np.concatenate((note_cols, age_cols))
df = raw_df[good_cols].copy()

# Gene expression as in email
# df = short_df[short_df["HGVSc"] == "ENST00000257430.4:c.835-8A>G"]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6501 entries, 0 to 6500
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Gene                  6501 non-null   object
 1   Sample ID             6501 non-null   object
 2   Cancer Type Detailed  6501 non-null   object
 3   Mutation Type         6501 non-null   object
 4   Variant Type          6498 non-null   object
 5   HGVSc                 5660 non-null   object
 6   MS                    3188 non-null   object
 7   Protein Change        6501 non-null   object
 8   Functional Impact     6501 non-null   object
 9   Diagnosis Age         3096 non-null   float64
 10  Age at Diagnosis      1477 non-null   float64
 11  Age At Diagnosis      304 non-null    float64
dtypes: float64(3), object(9)
memory usage: 609.6+ KB

In [52]:
# Stolen bfill from you! Axis = 1 looks across columns
df.loc[:, 'Age'] = df[age_cols].bfill(axis = 1).iloc[:, 0]
df = df.drop(columns = age_cols)

In [53]:
early_age = 50
df["Early Onset"] = df["Age"] < early_age
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6501 entries, 0 to 6500
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Gene                  6501 non-null   object
 1   Sample ID             6501 non-null   object
 2   Cancer Type Detailed  6501 non-null   object
 3   Mutation Type         6501 non-null   object
 4   Variant Type          6498 non-null   object
 5   HGVSc                 5660 non-null   object
 6   MS                    3188 non-null   object
 7   Protein Change        6501 non-null   object
 8   Functional Impact     6501 non-null   object
 9   Age                   4877 non-null   float64
 10  Early Onset           6501 non-null   bool
dtypes: bool(1), float64(1), object(9)
memory usage: 514.4+ KB

In [54]:
df = df.dropna(subset = ["Age"], axis = 0)
df = df.drop_duplicates(subset = ["Sample ID", "HGVSc"], keep = "first")

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4464 entries, 0 to 6500
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Gene                  4464 non-null   object
 1   Sample ID             4464 non-null   object
 2   Cancer Type Detailed  4464 non-null   object
 3   Mutation Type         4464 non-null   object
 4   Variant Type          4461 non-null   object
 5   HGVSc                 4025 non-null   object
 6   MS                    1308 non-null   object
 7   Protein Change        4464 non-null   object
 8   Functional Impact     4464 non-null   object
 9   Age                   4464 non-null   float64
 10  Early Onset           4464 non-null   bool
dtypes: bool(1), float64(1), object(9)
memory usage: 388.0+ KB

In [56]:
df.shape

(4464, 11)

In [57]:
df["Early Onset"].value_counts()

Early Onset
False    3586
True      878
Name: count, dtype: int64

In [58]:
df["Sample ID"]

0               TCGA-AA-A010-01
3               TCGA-EI-6917-01
4       coadread_dfci_2016_3235
5       coadread_dfci_2016_2367
6             P-0006759-T01-IM5
                 ...
6494          P-0009842-T01-IM5
6495          P-0010238-T01-IM5
6496          P-0013828-T01-IM5
6499          P-0010742-T01-IM5
6500          P-0014026-T01-IM5
Name: Sample ID, Length: 4464, dtype: object

In [59]:
# Lists with the IDs of both, early onset and not early onset
IDs_Early_list = list(df["Sample ID"][df["Early Onset"]])
print(len(IDs_Early_list))
IDs_Not_Early_list = list(df["Sample ID"][df["Early Onset"] == False])
print(len(IDs_Not_Early_list))
print(IDs_Early_list)
print(IDs_Not_Early_list)

878
3586
['TCGA-AA-A010-01', 'TCGA-EI-6917-01', 'P-0010049-T01-IM5', 'P-0006365-T01-IM5', 'CRC812_NT', 'TCGA-AG-A002-01', 'P-0009971-T01-IM5', 'CRC642_NT', 'P-0012402-T01-IM5', 'P-0006202-T01-IM5', 'TCGA-AY-A8YK-01', 'P-0001702-T01-IM3', 'P-0006766-T01-IM5', 'CRC1032_NT', 'P-0047886-T01-IM6', 'P-0013788-T01-IM5', 'SER-SILU-CC-P0384-PT-01', 'CRC916_NT', '05CO011', 'P-0001424-T01-IM3', 'P-0001424-T02-IM3', 'P-0000687-T01-IM3', 'P-0001685-T02-IM3', 'P-0003437-T01-IM5', 'P-0006758-T01-IM5', 'P-0007180-T01-IM5', 'P-0007279-T01-IM5', 'P-0008063-T01-IM5', 'P-0013894-T01-IM5', 'CRC585_NT', 'CRC802_NT', 'CRC943_NT', 'CRC943_NT', 'TCGA-CK-4947-01', 'P-0001690-T01-IM3', 'P-0002770-T01-IM3', 'P-0003796-T01-IM5', 'P-0004159-T01-IM5', 'P-0005908-T01-IM5', 'P-0006075-T01-IM5', 'P-0006230-T01-IM5', 'P-0007092-T01-IM5', 'P-0007740-T01-IM5', 'P-0008317-T01-IM5', 'P-0008652-T01-IM5', 'P-0009690-T01-IM5', 'P-0010138-T01-IM5', 'P-0010207-T01-IM5', 'P-0014296-T01-IM6', 'CRC141_NT', 'CRC560_NT', 'CRC609_NT', 's_PK_crc_089_T', 'TCGA-F4-6856-01', 'SER-SILU-CC-P0451-PT-01', 'TCGA-CM-6164-01', 'P-0015416-T01-IM6', 'P-0000868-T01-IM3', 'P-0001302-T01-IM3', 'P-0001685-T01-IM3', 'P-0001685-T02-IM3', 'P-0006075-T01-IM5', 'P-0006657-T01-IM5', 'P-0007112-T01-IM5', 'P-0008068-T01-IM5', 'P-0008317-T01-IM5', 'P-0013400-T01-IM5', 'P-0014296-T01-IM6', 'CRC235_NT', 'CRC852_NT', 'P-0009712-T01-IM5', 'P-0040508-T01-IM6', 'P-0039163-T03-IM6', 'P-0002048-T01-IM3', 'P-0003365-T01-IM5', 'P-0003575-T01-IM5', 'P-0003710-T01-IM5', 'P-0004159-T01-IM5', 'P-0004369-T01-IM5', 'P-0007631-T01-IM5', 'P-0008534-T01-IM5', 'P-0009341-T01-IM5', 'P-0010049-T01-IM5', 'P-0010364-T01-IM5', 'P-0010393-T01-IM5', 'P-0012281-T01-IM5', 'P-0013096-T01-IM5', 'P-0013285-T01-IM5', 'P-0014119-T01-IM5', 'P-0000933-T01-IM3', 'P-0001702-T01-IM3', 'P-0003308-T01-IM5', 'P-0003582-T01-IM5', 'P-0006135-T01-IM5', 'P-0006715-T01-IM5', 'P-0006743-T01-IM5', 'P-0007686-T01-IM5', 'P-0008075-T01-IM5', 'P-0011255-T01-IM5', 'P-0013263-T01-IM5', 'P-0014195-T01-IM6', 'CRC560_NT', 'CRC817_NT', 'P-0036503-T01-IM6', 'CRC566_NT', 'P-0007147-T01-IM5', 'CRC1211_NT', 'TCGA-CK-4952-01', 'P-0004698-T01-IM5', 'P-0007391-T01-IM5', 'CRC569_NT', '11CO070', 'TCGA-SS-A7HO-01', 'P-0006548-T01-IM5', 's_PK_crc_106_T', 'TCGA-EI-6917-01', 'CRC1141_NT', 'P-0010832-T01-IM5', 'P-0005326-T01-IM5', 'TCGA-CM-6674-01', 'CRC607_NT', 'P-0003110-T01-IM5', 'P-0001295-T01-IM3', 'CRC938_NT', 'TCGA-AA-A01S-01', 'CRC663_NT', 'P-0002049-T01-IM3', 'TCGA-AH-6897-01', 'P-0007305-T01-IM5', 'P-0007377-T02-IM5', 'P-0001767-T01-IM3', 'P-0012419-T01-IM5', 'CRC296_NT', 'CRC576_NT', 'P-0001685-T01-IM3', 'P-0006608-T01-IM5', 'P-0010275-T01-IM5', 'CRC520_NT', 'P-0001215-T01-IM3', 'CRC271_NT', 'SER-SILU-CC-P0155-PT-01', 'SER-SILU-CC-P0451-PT-01', 'P-0001347-T02-IM5', 'P-0004172-T01-IM5', 'P-0004845-T01-IM5', 'P-0004862-T01-IM5', 'P-0007272-T01-IM5', 'P-0010275-T01-IM5', 'CRC722_NT', 'CRC642_NT', 'TCGA-AA-A010-01', 'CRC1141_NT', 'P-0000526-T01-IM3', 'P-0000699-T01-IM3', 'P-0005858-T01-IM5', 'P-0009139-T01-IM5', 'P-0025161-T01-IM6', 'P-0006589-T01-IM5', 'CRC897_NT', 's_PK_crc_112_T', 'P-0002730-T01-IM3', 'TCGA-G4-6309-01', 'P-0003793-T01-IM5', 'P-0005801-T01-IM5', 'P-0007586-T01-IM5', 'P-0011158-T01-IM5', 'CRC1163_NT', 'CRC966_NT', 'P-0007771-T01-IM5', 'P-0003796-T01-IM5', 'P-0011226-T01-IM5', 'coadread_dfci_2016_43', 'TCGA-AA-3667-01', 'TCGA-AA-A01Q-01', 'TCGA-AA-A01S-01', 'TCGA-AA-A010-01', 'TCGA-AF-A56L-01', 'P-0002547-T01-IM3', 'P-0004362-T01-IM5', 'P-0007489-T01-IM5', 'P-0011195-T01-IM5', 'P-0011520-T01-IM5', 'CRC498_NT', 'CRC751_NT', 'CRC793_NT', 'CRC968_NT', 'P-0000714-T01-IM3', 's_PK_crc_134_T', 'CRC966_NT', 'P-0001316-T01-IM3', 'P-0003284-T01-IM5', 'P-0011306-T01-IM5', 'CRC972_NT', '11CO036', 'TCGA-A6-6781-01', 'CRC502_NT', 'CRC879_NT', 'P-0009114-T01-IM5', 'P-0001017-T01-IM3', 'CRC681_NT', 'TCGA-CM-6166-01', 'P-0009224-T02-IM5', 'P-0040977-T01-IM6', 'CRC884_NT', 'P-0047886-T01-IM6', 'P-0006394-T01-IM5', 'P-0008583-T01-IM5', 'SER-SILU-CC-P0189-PT-01', 'P-0002438-T01-IM3', 'TCGA-AF-3911-01', 'CRC994_NT', 'P-0010268-T01-IM5', 'P-0008467-T01-IM5', 'P-0007410-T01-IM5', 'P-0037482-T01-IM6', 'P-0006708-T01-IM5', 'CRC1071_NT', 'CRC1086_NT', 'P-0012402-T01-IM5', 'P-0000777-T01-IM3', 'P-0005824-T01-IM5', 'P-0013082-T01-IM5', 'P-0010062-T01-IM5', 'P-0005858-T01-IM5', 's_PK_crc_119_T', 'TCGA-EI-6917-01', 'P-0010504-T01-IM5', 'CRC609_NT', 'TCGA-D5-6929-01', 'P-0000561-T01-IM3', 'P-0010665-T01-IM5', 'P-0007226-T01-IM5', 'P-0011374-T01-IM5', 'CRC1079_NT', 'P-0009971-T01-IM5', 'TCGA-AG-A002-01', 'CRC38_NT', 'P-0007296-T01-IM5', 'coadread_dfci_2016_688', 'TCGA-AA-3692-01', 'P-0003755-T01-IM5', 'P-0006693-T01-IM5', 'P-0006863-T01-IM5', 'P-0008226-T02-IM5', 'P-0012402-T01-IM5', 'CRC139_NT', 'CRC351_NT', 'CRC566_NT', 'CRC659_NT', 'CRC703_NT', 'CRC777_NT', 'P-0003575-T01-IM5', 'CRC1022_NT', 'P-0005189-T01-IM5', 'P-0047886-T01-IM6', 'CRC773_NT', 'P-0002251-T01-IM3', 'P-0009433-T01-IM5', 'SER-SILU-CC-P0239-PT-01', 'P-0009751-T01-IM5', 'SER-SILU-CC-P0230-PT-01', 'coadread_dfci_2016_2369', 'TCGA-AA-A01R-01', 'TCGA-5M-AAT6-01', 'TCGA-CI-6620-01', 'TCGA-CI-6623-01', 'TCGA-DC-6157-01', 'TCGA-G4-6293-01', 'P-0004783-T01-IM5', 'P-0036503-T01-IM6', 'P-0001964-T01-IM3', 'P-0003130-T01-IM5', 'P-0003901-T01-IM5', 'P-0004486-T01-IM5', 'P-0005439-T01-IM5', 'P-0005589-T01-IM5', 'P-0005824-T01-IM5', 'P-0006659-T01-IM5', 'P-0007090-T02-IM5', 'P-0007097-T01-IM5', 'P-0007657-T01-IM5', 'P-0007990-T01-IM5', 'P-0008267-T01-IM5', 'P-0009305-T01-IM5', 'P-0011226-T01-IM5', 'P-0011287-T01-IM5', 'P-0012406-T01-IM5', 'P-0012823-T01-IM5', 'P-0012823-T02-IM5', 'P-0013277-T01-IM5', 'P-0013400-T01-IM5', 'P-0014119-T01-IM5', 'CRC1196_NT', 'CRC763_NT', 'CRC781_NT', 'CRC860_NT', 'P-0005634-T01-IM5', 'P-0009830-T01-IM5', 'P-0003474-T01-IM5', 'P-0005384-T01-IM5', 'P-0003254-T01-IM5', 'CRC834_NT', 'P-0002994-T01-IM3', 'CRC1066_NT', 'P-0003285-T01-IM5', 'P-0006093-T01-IM5', 'P-0007069-T01-IM5', 'P-0010203-T01-IM5', 'P-0003077-T01-IM5', 'CRC724_NT', 'TCGA-4T-AA8H-01', 'P-0002407-T01-IM3', 'P-0008042-T01-IM5', 'P-0004968-T01-IM5', 'P-0000933-T01-IM3', 'TCGA-F4-6461-01', 'P-0012268-T01-IM5', 'P-0006750-T01-IM5', 'CRC778_NT', 'SER-SILU-CC-P0206-PT-01', 'P-0002035-T01-IM3', 'P-0012281-T01-IM5', 'P-0005824-T01-IM5', 'CRC1089_NT', 'TCGA-AH-6903-01', 'P-0009650-T01-IM5', 'P-0013772-T01-IM5', 'CRC659_NT', 'P-0009830-T01-IM5', 'P-0001647-T01-IM3', 'P-0014010-T01-IM5', 'P-0010364-T01-IM5', 'TCGA-AY-A8YK-01', 'P-0011144-T01-IM5', 's_PK_crc_127_T', 'P-0006704-T01-IM5', 'TCGA-CK-4948-01', 'P-0006669-T01-IM5', 'P-0012032-T01-IM5', 'P-0007804-T01-IM5', 'SER-SILU-CC-P0189-PT-01', 'P-0004350-T01-IM5', 'P-0011347-T01-IM5', 'P-0009488-T01-IM5', 'P-0005998-T01-IM5', 'P-0006770-T01-IM5', 'P-0007115-T01-IM5', 'CRC180_NT', 'P-0010367-T01-IM5', 'P-0007486-T01-IM5', 'P-0007144-T01-IM5', '24CO005', 'TCGA-CA-6718-01', 'TCGA-EI-6508-01', 'TCGA-EI-6917-01', 'TCGA-G4-6307-01', 'P-0038423-T01-IM6', 'P-0000994-T01-IM3', 'P-0001459-T01-IM3', 'P-0007216-T01-IM5', 'P-0007368-T01-IM5', 'P-0009902-T01-IM5', 'P-0010365-T01-IM5', 'P-0013285-T01-IM5', 'P-0013787-T01-IM5', 'CRC1141_NT', 'CRC1211_NT', 'CRC291_NT', 'CRC371_NT', 'CRC609_NT', 'CRC659_NT', 'CRC843_NT', 'P-0008534-T01-IM5', 'P-0007631-T01-IM5', 'CRC133_NT', 'SER-SILU-CC-P0237-PT-01', 'P-0000241-T01-IM3', 'TCGA-AZ-4308-01', 'P-0001200-T01-IM3', 'P-0011131-T01-IM5', 'P-0000493-T01-IM3', 'P-0007092-T01-IM5', 'P-0013088-T01-IM5', 'P-0003796-T01-IM5', 'P-0005824-T01-IM5', 'TCGA-AH-6897-01', 'P-0001394-T02-IM5', 'P-0005381-T01-IM5', 'P-0008652-T01-IM5', 's_PK_crc_025_T', 'P-0006737-T01-IM5', 'P-0006213-T01-IM5', 'P-0008031-T01-IM5', 'P-0001237-T01-IM3', 'P-0004872-T01-IM5', 'P-0006888-T01-IM5', 'P-0012110-T01-IM5', 'P-0001302-T01-IM3', 'P-0003254-T01-IM5', 'P-0009830-T01-IM5', 'TCGA-AG-A00C-01', 'P-0011182-T01-IM5', 'P-0005824-T01-IM5', 'P-0001192-T01-IM3', 'P-0006000-T02-IM5', 'P-0007843-T01-IM5', 'P-0005326-T01-IM5', 'P-0013929-T01-IM5', 'P-0001318-T01-IM3', 'P-0006365-T01-IM5', 's_PK_crc_134_T', 'P-0010535-T01-IM5', 'P-0000772-T01-IM3', 'P-0003397-T01-IM5', 'CRC607_NT', 'TCGA-AF-A56N-01', 'P-0001237-T01-IM3', 'P-0006271-T01-IM5', 'CRC897_NT', 'SER-SILU-CC-P0239-PT-01', 'P-0009838-T01-IM5', 'P-0012402-T01-IM5', 'TCGA-AG-A01Y-01', 'P-0004698-T01-IM5', 'P-0006706-T01-IM5', 'P-0002994-T01-IM3', 'P-0003582-T01-IM5', 'P-0011484-T01-IM5', 'P-0004872-T01-IM5', 'P-0007664-T01-IM5', 'P-0027427-T01-IM6', 'P-0007136-T01-IM5', 'P-0009062-T01-IM5', 'P-0009690-T01-IM5', 'P-0011283-T01-IM5', 'P-0012268-T01-IM5', 'P-0012447-T01-IM5', 's_PK_crc_114_T', 'P-0000777-T01-IM3', 'P-0000860-T01-IM3', 'P-0010146-T01-IM5', 'P-0011306-T01-IM5', 'CRC935_NT', 'SER-SILU-CC-P0384-PT-01', 'TCGA-DC-4745-01', 'TCGA-EI-6508-01', 'P-0005715-T01-IM5', 'P-0006761-T01-IM5', 'P-0012135-T01-IM5', 'SER-SILU-CC-P0002-PT-01', 'P-0016091-T01-IM6', 'P-0002678-T01-IM3', 'P-0002855-T01-IM3', 'P-0005163-T01-IM5', 'P-0005381-T01-IM5', 'P-0005634-T01-IM5', 'P-0005730-T02-IM5', 'P-0007588-T01-IM5', 'P-0008019-T01-IM5', 'P-0009302-T01-IM5', 'P-0010138-T01-IM5', 'P-0010742-T01-IM5', 'P-0012810-T01-IM5', 's_PK_crc_078_T', 'CRC764_NT', 'CRC916_NT', 'TCGA-CI-6623-01', 'P-0006967-T01-IM5', 'P-0003755-T01-IM5', 'TCGA-CK-6748-01', 'P-0000742-T01-IM3', 'P-0009971-T01-IM5', 'P-0005029-T01-IM5', 'P-0008541-T01-IM5', 'P-0013263-T01-IM5', 'TCGA-AF-3911-01', 'P-0010407-T01-IM5', 'P-0010535-T01-IM5', 'TCGA-A6-5662-01', 'P-0006822-T01-IM5', 'CRC663_NT', 'TCGA-CM-6166-01', 'P-0010504-T01-IM5', 'P-0013156-T01-IM5', 'P-0004886-T01-IM5', 'CRC1080_NT', 'SER-SILU-CC-P0132-PT-01', 'P-0014168-T01-IM5', 'P-0040508-T01-IM6', 'P-0001913-T01-IM3', 'P-0001913-T02-IM5', 'P-0002049-T01-IM3', 'P-0003011-T01-IM3', 'P-0006865-T01-IM5', 'P-0009972-T01-IM5', 'TCGA-CM-6166-01', 'P-0003308-T01-IM5', 'P-0001531-T01-IM3', 'P-0002048-T01-IM3', 'P-0002251-T01-IM3', 'P-0004692-T01-IM5', 'TCGA-AF-2691-01', 'P-0000911-T01-IM3', 'P-0001531-T01-IM3', 'P-0007180-T01-IM5', 'P-0008267-T01-IM5', 'P-0006706-T01-IM5', 'P-0002251-T01-IM3', 'P-0006706-T01-IM5', 'P-0007669-T01-IM5', 'P-0007112-T01-IM5', 'P-0007654-T01-IM5', 'P-0010665-T01-IM5', 'P-0011195-T01-IM5', 'P-0007669-T01-IM5', 'P-0005528-T01-IM5', 'P-0009114-T01-IM5', 'P-0003154-T01-IM5', 'P-0014415-T01-IM6', 'TCGA-CI-6619-01', 'P-0006770-T01-IM5', 'P-0003301-T01-IM5', 'P-0009302-T01-IM5', 'TCGA-CM-6166-01', 'P-0006213-T01-IM5', 'coadread_dfci_2016_2388', 'P-0000798-T01-IM3', 'P-0006135-T01-IM5', 'P-0007081-T02-IM5', 'CRC1077_NT', 'TCGA-CM-6166-01', 'TCGA-CM-5344-01', 'TCGA-AA-3692-01', 'P-0001690-T01-IM3', 'P-0006575-T01-IM5', 'P-0006726-T01-IM5', 'P-0006575-T01-IM5', 'TCGA-A6-5667-01', 'P-0002804-T01-IM3', 'P-0011255-T01-IM5', 'P-0012878-T01-IM5', 'CRC585_NT', 'P-0001771-T01-IM3', 'P-0009192-T01-IM5', 'P-0010367-T01-IM5', 'TCGA-AF-A56L-01', 'TCGA-AA-3955-01', 'P-0007869-T01-IM5', 'P-0009851-T01-IM5', 'P-0003130-T01-IM5', 'P-0007883-T01-IM5', 'P-0008075-T01-IM5', 'CRC1079_NT', 'CRC1137_NT', 'TCGA-AG-A00C-01', 'P-0001499-T01-IM3', 'P-0002042-T01-IM3', 'P-0006708-T01-IM5', 'P-0007654-T01-IM5', 'P-0010203-T01-IM5', 'P-0010268-T01-IM5', 'CRC326_NT', 'P-0006394-T01-IM5', 'TCGA-AA-3667-01', 'P-0001767-T01-IM3', 'P-0005858-T01-IM5', 'TCGA-AG-A002-01', 'P-0006721-T01-IM5', 'TCGA-CM-6166-01', 'TCGA-CM-6166-01', 'P-0006275-T01-IM5', 'P-0007126-T01-IM5', 'P-0007126-T02-IM5', 'P-0008031-T01-IM5', 'P-0012823-T01-IM5', 'P-0012823-T02-IM5', 'CRC99_NT', 'P-0006704-T01-IM5', 'P-0015416-T01-IM6', 'P-0001647-T01-IM3', 'P-0013277-T01-IM5', 'CRC1196_NT', 'CRC202_NT', 'P-0007586-T01-IM5', '11CO036', 'P-0007097-T01-IM5', 'P-0009902-T01-IM5', 'P-0008063-T01-IM5', 'P-0011144-T01-IM5', 'P-0025161-T01-IM6', 'P-0001200-T01-IM3', 'P-0006589-T01-IM5', 'P-0010243-T01-IM5', '05CO011', 'P-0000754-T01-IM3', 'TCGA-DC-6157-01', 'TCGA-F4-6461-01', 'P-0004783-T01-IM5', 'P-0039163-T03-IM6', 'P-0000737-T01-IM3', 'P-0003437-T01-IM5', 'P-0004845-T01-IM5', 'P-0006981-T01-IM5', 'P-0007216-T01-IM5', 'P-0007368-T01-IM5', 'P-0007691-T01-IM5', 'P-0014195-T01-IM6', 'CRC879_NT', 'P-0000772-T01-IM3', 'P-0011182-T01-IM5', 'P-0004350-T01-IM5', 'TCGA-AA-3872-01', 'P-0001347-T02-IM5', 'P-0006230-T01-IM5', 'P-0007391-T01-IM5', 'CRC763_NT', 'CRC659_NT', 'SER-SILU-CC-P0230-PT-01', 'coadread_dfci_2016_2369', 'P-0003780-T01-IM5', 'P-0003474-T01-IM5', 'coadread_dfci_2016_3298', 'TCGA-AA-A010-01', 'TCGA-AA-A01R-01', 'TCGA-AG-A002-01', 'P-0036503-T01-IM6', 'P-0040977-T01-IM6', 'P-0005888-T01-IM5', 'P-0005908-T01-IM5', 'P-0006138-T01-IM5', 'P-0006863-T01-IM5', 'P-0007115-T01-IM5', 'P-0007804-T01-IM5', 'P-0007990-T01-IM5', 'P-0009224-T02-IM5', 'P-0011226-T01-IM5', 'P-0011287-T01-IM5', 'P-0012402-T01-IM5', 'CRC1022_NT', 'CRC22_NT', 'CRC502_NT', 'CRC566_NT', 'CRC860_NT', 'P-0007144-T01-IM5', 'CRC843_NT', 'P-0005589-T01-IM5', 'P-0006758-T01-IM5', 'TCGA-5M-AAT6-01', 'P-0010139-T01-IM5', 'P-0006758-T01-IM5', 'P-0004362-T01-IM5', 'P-0005987-T01-IM5', 'P-0013082-T01-IM5', 'P-0013400-T01-IM5', 'P-0013787-T01-IM5', 'P-0009305-T01-IM5', 'TCGA-G4-6309-01', 'P-0000241-T01-IM3', 'P-0000561-T01-IM3', 'P-0001295-T01-IM3', 'P-0004968-T01-IM5', 'P-0005011-T01-IM5', 'P-0005326-T01-IM5', 'P-0007090-T02-IM5', 'P-0007296-T01-IM5', 'P-0009830-T01-IM5', 'P-0010710-T01-IM5', 's_PK_crc_025_T', 's_PK_crc_093_T', 's_PK_crc_106_T', 'P-0003990-T01-IM3', 'CRC852_NT', 'P-0011158-T01-IM5', 'P-0006659-T01-IM5', 'P-0006737-T01-IM5', 'P-0007135-T01-IM5', 'P-0013982-T01-IM5', 'P-0007039-T01-IM5', '11CO070', 'TCGA-EI-6917-01', 'P-0000687-T01-IM3', 'P-0003348-T01-IM5', 'P-0010074-T01-IM5', 'P-0011131-T01-IM5', 'CRC1163_NT', 'CRC681_NT', 'CRC703_NT', 'P-0006669-T01-IM5', 'CRC139_NT', 'TCGA-4T-AA8H-01', 'TCGA-G4-6293-01', 'P-0007377-T02-IM5', 'coadread_dfci_2016_688', 'P-0003285-T01-IM5', 'P-0005439-T01-IM5', 'P-0007181-T01-IM5', 'P-0013772-T01-IM5', 'CRC569_NT', 'CRC778_NT', 'P-0001054-T01-IM3', 'P-0001054-T02-IM3', 'P-0012032-T01-IM5', 'CRC793_NT', 'SER-SILU-CC-P0155-PT-01', 'P-0009751-T01-IM5', 'CRC931_NT', 'P-0038423-T01-IM6', 'P-0004172-T01-IM5', 'coadread_dfci_2016_43', 'P-0011520-T01-IM5', 'P-0004486-T01-IM5', 'P-0008467-T01-IM5', 'CRC613_NT', 'P-0009016-T01-IM5', 'CRC1071_NT', 'P-0007272-T01-IM5', 'P-0006548-T01-IM5', 'P-0007069-T01-IM5', 'TCGA-AG-A002-01', 'P-0001215-T01-IM3', 'P-0009760-T01-IM5', 'P-0010406-T01-IM5', 'P-0014010-T01-IM5', 'TCGA-SS-A7HO-01', 'P-0013055-T01-IM5', 'SER-SILU-CC-P0189-PT-01', 'coadread_dfci_2016_3298', 'TCGA-CA-6718-01', 'TCGA-CK-4952-01', 'TCGA-NH-A50U-01', 'P-0015416-T01-IM6', 'P-0048091-T01-IM6', 'P-0000511-T01-IM3', 'P-0001424-T01-IM3', 'P-0001424-T02-IM3', 'P-0001685-T02-IM3', 'P-0003901-T01-IM5', 'P-0005987-T01-IM5', 'P-0008226-T02-IM5', 'P-0010710-T01-IM5', 's_PK_crc_096_T', 's_PK_crc_112_T', 'CRC609_NT', 'CRC613_NT', 'CRC834_NT', 'CRC861_NT', 'CRC888_NT', 'CRC894_NT', 'CRC966_NT', 'P-0000714-T01-IM3', 's_PK_crc_114_T', 'CRC38_NT', 'P-0005824-T01-IM5', 'CRC1141_NT', 'P-0001316-T01-IM3', 'P-0010062-T01-IM5', 'P-0003284-T01-IM5', 'P-0006888-T01-IM5', 'CRC648_NT', 'P-0010112-T01-IM5', 'P-0010238-T01-IM5', 'P-0001394-T02-IM5', 'P-0005634-T01-IM5', 'P-0001215-T01-IM3', 'P-0010238-T01-IM5', 'P-0010238-T01-IM5', 'CRC703_NT', 'CRC663_NT', 'P-0001215-T01-IM3', 'P-0005824-T01-IM5', 'CRC28_NT', 'P-0036503-T01-IM6', 'TCGA-CM-6162-01', 'P-0005987-T01-IM5', 'P-0013876-T01-IM5', 'P-0013300-T01-IM5', 'TCGA-G4-6293-01', 'P-0001685-T01-IM3', 'P-0012402-T01-IM5', 'P-0012402-T01-IM5', 'P-0001215-T01-IM3', 'P-0005824-T01-IM5', 'P-0010504-T01-IM5', 's_PK_crc_106_T', '11CO070', 'CRC566_NT', 'CRC566_NT', 'P-0012402-T01-IM5', 'CRC127_NT', 'P-0001215-T01-IM3', 'P-0008317-T01-IM5', 'P-0006863-T01-IM5', 'P-0013227-T01-IM5', 'CRC566_NT', 'CRC590_NT', 'CRC703_NT', 'P-0004362-T01-IM5', 'TCGA-CM-5860-01', 'P-0006548-T01-IM5', 'CRC1141_NT', 'CRC724_NT', 'CRC843_NT', 'P-0007296-T01-IM5', 'CRC474_NT', 'P-0047886-T01-IM6', 'CRC474_NT', 'CRC724_NT', 'TCGA-AA-A010-01', 'P-0005824-T01-IM5', 'CRC950_NT', 'CRC1141_NT', 'P-0013227-T01-IM5', '11CO070', 'TCGA-AA-A01Q-01', 'CRC215_NT', 'P-0000241-T01-IM3', '11CO070', 'CRC566_NT', 'P-0013227-T01-IM5', 'P-0013400-T01-IM5', 'CRC807_NT', 'CRC474_NT', 'coadread_dfci_2016_2369', 'P-0036503-T01-IM6', 'TCGA-SS-A7HO-01', 'P-0005824-T01-IM5', 'P-0005824-T01-IM5', 'TCGA-AG-A002-01', 'TCGA-4T-AA8H-01', 'TCGA-5M-AAT6-01', 'TCGA-A6-5662-01', 'TCGA-A6-5667-01', 'TCGA-AA-3667-01', 'TCGA-AA-3692-01', 'TCGA-AA-3872-01', 'TCGA-AA-3955-01', 'TCGA-AA-A010-01', 'TCGA-AA-A01R-01', 'TCGA-AA-A01S-01', 'TCGA-AY-A8YK-01', 'TCGA-AZ-4308-01', 'TCGA-AZ-4684-01', 'TCGA-CA-6718-01', 'TCGA-CK-4947-01', 'TCGA-CK-4948-01', 'TCGA-CK-4952-01', 'TCGA-CK-6748-01', 'TCGA-CM-5344-01', 'TCGA-CM-5860-01', 'TCGA-CM-6164-01', 'TCGA-CM-6166-01', 'TCGA-D5-6929-01', 'TCGA-F4-6461-01', 'TCGA-G4-6293-01', 'TCGA-G4-6307-01', 'TCGA-G4-6309-01', 'TCGA-NH-A50U-01', 'TCGA-SS-A7HO-01', 'TCGA-AF-3911-01', 'TCGA-AF-A56L-01', 'TCGA-AF-A56N-01', 'TCGA-AG-A002-01', 'TCGA-AG-A00C-01', 'TCGA-AG-A01Y-01', 'TCGA-AH-6897-01', 'TCGA-AH-6903-01', 'TCGA-CI-6619-01', 'TCGA-CI-6620-01', 'TCGA-CI-6623-01', 'TCGA-DC-4745-01', 'TCGA-DC-6157-01', 'TCGA-DC-6683-01', 'TCGA-EI-6508-01', 'TCGA-EI-6917-01', 'TCGA-A6-6781-01', 'TCGA-CM-6674-01', 'P-0010238-T01-IM5', 'P-0010742-T01-IM5']

# Early Onset

In [60]:
import requests
import pandas as pd
import pandas as pd
from pyfaidx import Fasta # might need to do pip install first


base_url = "https://www.cbioportal.org/api"

# Choose study
profile = "crc_msk_2017_mutations"

# Choose sample ids the 35 IDs
sample_ids = IDs_Early_list

payload = {"sampleIds": sample_ids}

headers = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

r = requests.post(
    f"{base_url}/molecular-profiles/{profile}/mutations/fetch",
    json=payload,
    headers=headers
)

mut = pd.DataFrame(r.json())

mut.to_csv("all_mutations_crc_msk2017_samples_Early_Onset.csv", index=False)


# repeat if there are >1 studies, and merge into a single mut file

In [61]:
mut.head()

,uniqueSampleKey,uniquePatientKey,molecularProfileId,sampleId,patientId,entrezGeneId,studyId,center,mutationStatus,validationStatus,...,proteinChange,mutationType,ncbiBuild,variantType,keyword,chr,variantAllele,refseqMrnaId,proteinPosStart,proteinPosEnd
0,UC0wMDAwMjQxLVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMjQxOmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000241-T01-IM3,P-0000241,324,crc_msk_2017,MSKCC,NA,NA,...,D1134Efs*3,Frame_Shift_Del,GRCh37,DEL,APC truncating,5,-,NM_000038.5,1134,1134
1,UC0wMDAwMjQxLVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMjQxOmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000241-T01-IM3,P-0000241,324,crc_msk_2017,MSKCC,NA,NA,...,R2530W,Missense_Mutation,GRCh37,SNP,APC R2530 missense,5,T,NA,2530,2530
2,UC0wMDAwMjQxLVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMjQxOmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000241-T01-IM3,P-0000241,324,crc_msk_2017,MSKCC,NA,NA,...,S1465Wfs*3,Frame_Shift_Del,GRCh37,DEL,APC truncating,5,-,NM_000038.5,1462,1465
3,UC0wMDAwMjQxLVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMjQxOmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000241-T01-IM3,P-0000241,2065,crc_msk_2017,MSKCC,NA,NA,...,A232V,Missense_Mutation,GRCh37,SNP,ERBB3 A232 missense,12,T,NM_001982.3,232,232
4,UC0wMDAwMjQxLVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMjQxOmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000241-T01-IM3,P-0000241,3845,crc_msk_2017,MSKCC,NA,NA,...,G12C,Missense_Mutation,GRCh37,SNP,KRAS G12 missense,12,A,NM_033360.2,12,12

In [62]:
mut.shape

(4362, 27)

In [63]:
mut[["sampleId", "mutationStatus", "referenceAllele", "proteinChange", "mutationType",
      "variantType", "keyword", "chr", "variantAllele"]].head()

,sampleId,mutationStatus,referenceAllele,proteinChange,mutationType,variantType,keyword,chr,variantAllele
0,P-0000241-T01-IM3,NA,CTATG,D1134Efs*3,Frame_Shift_Del,DEL,APC truncating,5,-
1,P-0000241-T01-IM3,NA,C,R2530W,Missense_Mutation,SNP,APC R2530 missense,5,T
2,P-0000241-T01-IM3,NA,AG,S1465Wfs*3,Frame_Shift_Del,DEL,APC truncating,5,-
3,P-0000241-T01-IM3,NA,C,A232V,Missense_Mutation,SNP,ERBB3 A232 missense,12,T
4,P-0000241-T01-IM3,NA,C,G12C,Missense_Mutation,SNP,KRAS G12 missense,12,A

In [64]:
import numpy as np
print(mut.columns)
print("Total recorded mutations:", len(mut))
grouped = mut[["sampleId", "mutationType", "referenceAllele"]].groupby("sampleId")#.count()
print("Total recorded patients:", len(grouped))
print("Average mutations recorded per sample:", np.mean(grouped.count()))
grouped.count()
# mut.head()

Index(['uniqueSampleKey', 'uniquePatientKey', 'molecularProfileId', 'sampleId',
       'patientId', 'entrezGeneId', 'studyId', 'center', 'mutationStatus',
       'validationStatus', 'tumorAltCount', 'tumorRefCount', 'normalAltCount',
       'normalRefCount', 'startPosition', 'endPosition', 'referenceAllele',
       'proteinChange', 'mutationType', 'ncbiBuild', 'variantType', 'keyword',
       'chr', 'variantAllele', 'refseqMrnaId', 'proteinPosStart',
       'proteinPosEnd'],
      dtype='object')
Total recorded mutations: 4362
Total recorded patients: 314
Average mutations recorded per sample: 13.89171974522293

                   mutationType  referenceAllele
sampleId
P-0000241-T01-IM3             8                8
P-0000493-T01-IM3             4                4
P-0000511-T01-IM3             4                4
P-0000526-T01-IM3             6                6
P-0000561-T01-IM3            23               23
...                         ...              ...
P-0014119-T01-IM5             6                6
P-0014168-T01-IM5             7                7
P-0014195-T01-IM6             6                6
P-0014296-T01-IM6            10               10
P-0014415-T01-IM6             4                4

[314 rows x 2 columns]

In [65]:
import pandas as pd
from pyfaidx import Fasta

# -----------------------------
# Inputs
# -----------------------------
mut = pd.read_csv("all_mutations_crc_msk2017_samples_Early_Onset.csv")

# Change this path if needed
fasta_path = "data/hg19.fa"
ref = Fasta(fasta_path)

# -----------------------------
# Basic cleanup / added columns
# -----------------------------
mut = mut.copy()

# cBioPortal export uses 'keyword' as gene symbol here
mut["gene"] = mut["keyword"]

# HGVSc is not present in this export
mut["HGVSc"] = pd.NA

# Mark the specific target splice-creating mutation:
# chr5:112151184 A>G
mut["target splice"] = (
    mut["chr"].astype(str).str.replace(r"\.0$", "", regex=True).isin(["5", "chr5"]) &
    pd.to_numeric(mut["startPosition"], errors="coerce").eq(112151184) &
    mut["referenceAllele"].astype(str).str.upper().eq("A") &
    mut["variantAllele"].astype(str).str.upper().eq("G")
).astype(int)

# -----------------------------
# Keep all single-base substitutions
# This includes splice SNVs and splice-creating SNVs
# -----------------------------
is_sbs = (
    mut["referenceAllele"].astype(str).str.len().eq(1) &
    mut["variantAllele"].astype(str).str.len().eq(1) &
    mut["referenceAllele"].astype(str).str.upper().isin(list("ACGT")) &
    mut["variantAllele"].astype(str).str.upper().isin(list("ACGT"))
)

snv = mut.loc[is_sbs].copy()

# -----------------------------
# Helpers for COSMIC96 assignment
# -----------------------------
comp = str.maketrans("ACGT", "TGCA")

def revcomp(seq):
    return seq.translate(comp)[::-1]

def clean_chrom(chrom):
    chrom = str(chrom).strip()
    if chrom.endswith(".0"):
        chrom = chrom[:-2]
    return chrom

def get_context_pyfaidx(ref, chrom, pos1):
    chrom = clean_chrom(chrom)

    candidates = [chrom]
    if chrom.startswith("chr"):
        candidates.append(chrom.replace("chr", "", 1))
    else:
        candidates.append("chr" + chrom)

    used_chrom = None
    for c in candidates:
        if c in ref.keys():
            used_chrom = c
            break

    if used_chrom is None:
        raise KeyError(f"Chromosome {chrom} not found in FASTA")

    pos1 = int(pos1)

    # pyfaidx uses 0-based slicing, end-exclusive
    context = ref[used_chrom][pos1 - 2 : pos1 + 1].seq.upper()

    if len(context) != 3:
        return None, used_chrom

    return context, used_chrom

def to_cosmic96(context, ref_base, alt_base):
    context = context.upper()
    ref_base = ref_base.upper()
    alt_base = alt_base.upper()

    if len(context) != 3:
        return None

    if context[1] != ref_base:
        return None

    # Normalize to pyrimidine representation
    if ref_base in ["A", "G"]:
        context = revcomp(context)
        ref_base = revcomp(ref_base)
        alt_base = revcomp(alt_base)

    if ref_base not in ["C", "T"]:
        return None

    return f"{context[0]}[{ref_base}>{alt_base}]{context[2]}"

# -----------------------------
# Annotate trinucleotide context and COSMIC96
# -----------------------------
contexts = []
classes = []
problems = []
used_chrs = []

for _, row in snv.iterrows():
    try:
        context, used_chr = get_context_pyfaidx(ref, row["chr"], row["startPosition"])
        ref_base = str(row["referenceAllele"]).upper()
        alt_base = str(row["variantAllele"]).upper()

        cosmic = to_cosmic96(context, ref_base, alt_base)

        contexts.append(context)
        classes.append(cosmic)
        used_chrs.append(used_chr)

        if context is None:
            problems.append("Could not extract 3bp context")
        elif cosmic is None:
            problems.append(
                f"Reference allele mismatch: FASTA middle base={context[1]}, mutation ref={ref_base}"
            )
        else:
            problems.append(None)

    except Exception as e:
        contexts.append(None)
        classes.append(None)
        used_chrs.append(None)
        problems.append(str(e))

snv["used_chr"] = used_chrs
snv["trinuc_context"] = contexts
snv["COSMIC96"] = classes
snv["problem"] = problems

# -----------------------------
# Build final dataframe
# -----------------------------
final_df = snv[[
    "sampleId",
    "patientId",
    "gene",
    "HGVSc",
    "target splice",
    "chr",
    "used_chr",
    "startPosition",
    "endPosition",
    "referenceAllele",
    "variantAllele",
    "proteinChange",
    "mutationType",
    "variantType",
    "ncbiBuild",
    "trinuc_context",
    "COSMIC96",
    "problem"
]].copy()

# -----------------------------
# Save outputs
# -----------------------------
final_df.to_csv("all_mutations_crc_msk2017_samples_Early_Onset_cosmic96.csv", index=False)

counts = final_df["COSMIC96"].value_counts(dropna=True).sort_index()
counts.to_csv("Early_Onset_cosmic96_counts.csv", header=["count"])

# -----------------------------
# Checks
# -----------------------------
print(final_df.head(20))

print("\nTarget splice rows:")
print(
    final_df.loc[final_df["target splice"] == 1, [
        "sampleId",
        "gene",
        "proteinChange",
        "mutationType",
        "chr",
        "startPosition",
        "referenceAllele",
        "variantAllele",
        "trinuc_context",
        "COSMIC96",
        "problem"
    ]]
)

             sampleId  patientId                  gene HGVSc  target splice  \
1   P-0000241-T01-IM3  P-0000241    APC R2530 missense  <NA>              0
3   P-0000241-T01-IM3  P-0000241   ERBB3 A232 missense  <NA>              0
4   P-0000241-T01-IM3  P-0000241     KRAS G12 missense  <NA>              0
5   P-0000241-T01-IM3  P-0000241    PAK1 L470 missense  <NA>              0
6   P-0000241-T01-IM3  P-0000241  PTCH1 V1418 missense  <NA>              0
7   P-0000241-T01-IM3  P-0000241    TP53 R158 missense  <NA>              0
8   P-0000493-T01-IM3  P-0000493        APC truncating  <NA>              0
9   P-0000493-T01-IM3  P-0000493  PIK3CA C901 missense  <NA>              0
10  P-0000493-T01-IM3  P-0000493      PTCH1 truncating  <NA>              0
11  P-0000493-T01-IM3  P-0000493    TP53 R248 missense  <NA>              0
13  P-0000511-T01-IM3  P-0000511    BRAF K601 missense  <NA>              0
14  P-0000511-T01-IM3  P-0000511    TP53 R248 missense  <NA>              0
15  P-0000511-T01-IM3  P-0000511  KMT2D T2524 missense  <NA>              0
16  P-0000526-T01-IM3  P-0000526        APC truncating  <NA>              0
17  P-0000526-T01-IM3  P-0000526        ATM truncating  <NA>              0
18  P-0000526-T01-IM3  P-0000526     KRAS G12 missense  <NA>              0
19  P-0000526-T01-IM3  P-0000526  PTCH1 E1273 missense  <NA>              0
20  P-0000526-T01-IM3  P-0000526   HNF1A R321 missense  <NA>              0
21  P-0000526-T01-IM3  P-0000526     CIC E439 missense  <NA>              0
22  P-0000561-T01-IM3  P-0000561        APC truncating  <NA>              0

    chr used_chr  startPosition  endPosition referenceAllele variantAllele  \
1     5     chr5      112178879    112178879               C             T
3    12    chr12       56481660     56481660               C             T
4    12    chr12       25398285     25398285               C             A
5    11    chr11       77047135     77047135               A             T
6     9     chr9       98209286     98209286               C             T
7    17    chr17        7578457      7578457               C             T
8     5     chr5      112174784    112174784               A             T
9     3     chr3      178947827    178947827               G             T
10    9     chr9       98220489     98220489               C             A
11   17    chr17        7577539      7577539               G             A
13    7     chr7      140453134    140453134               T             C
14   17    chr17        7577538      7577538               C             T
15   12    chr12       49433982     49433982               G             A
16    5     chr5      112163677    112163677               A             T
17   11    chr11      108175528    108175528               C             T
18   12    chr12       25398284     25398284               C             T
19    9     chr9       98209721     98209721               C             T
20   12    chr12      121434070    121434070               C             T
21   19    chr19       42793513     42793513               G             A
22    5     chr5      112173572    112173572               G             T

   proteinChange       mutationType variantType ncbiBuild trinuc_context  \
1         R2530W  Missense_Mutation         SNP    GRCh37            ACG
3          A232V  Missense_Mutation         SNP    GRCh37            GCC
4           G12C  Missense_Mutation         SNP    GRCh37            CCA
5          L470Q  Missense_Mutation         SNP    GRCh37            CAG
6         V1418I  Missense_Mutation         SNP    GRCh37            ACG
7          R158H  Missense_Mutation         SNP    GRCh37            GCG
8         K1165*  Nonsense_Mutation         SNP    GRCh37            AAA
9          C901F  Missense_Mutation         SNP    GRCh37            TGT
10         E992*  Nonsense_Mutation         SNP    GRCh37            TCA
11         R248W  Missense_Mutation         SNP    GRCh37            CGG
13         K601E  Missense_Mutation         SNP    GRCh37            TTC
14         R248Q  Missense_Mutation         SNP    GRCh37            CCG
15        T2524M  Missense_Mutation         SNP    GRCh37            CGT
16         K534*  Nonsense_Mutation         SNP    GRCh37            AAA
17        R1875*  Nonsense_Mutation         SNP    GRCh37            TCG
18          G12D  Missense_Mutation         SNP    GRCh37            ACC
19        E1273K  Missense_Mutation         SNP    GRCh37            TCG
20         R321C  Missense_Mutation         SNP    GRCh37            GCG
21         E439K  Missense_Mutation         SNP    GRCh37            GGA
22         E761*  Nonsense_Mutation         SNP    GRCh37            AGA

   COSMIC96 problem
1   A[C>T]G    None
3   G[C>T]C    None
4   C[C>A]A    None
5   C[T>A]G    None
6   A[C>T]G    None
7   G[C>T]G    None
8   T[T>A]T    None
9   A[C>A]A    None
10  T[C>A]A    None
11  C[C>T]G    None
13  T[T>C]C    None
14  C[C>T]G    None
15  A[C>T]G    None
16  T[T>A]T    None
17  T[C>T]G    None
18  A[C>T]C    None
19  T[C>T]G    None
20  G[C>T]G    None
21  T[C>T]C    None
22  T[C>A]T    None

Target splice rows:
               sampleId            gene proteinChange     mutationType  chr  \
943   P-0003365-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
963   P-0003575-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
976   P-0003710-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
1035  P-0004159-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
1130  P-0004369-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2688  P-0007631-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2971  P-0008534-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3032  P-0009341-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3162  P-0010049-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3303  P-0010364-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3323  P-0010393-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3662  P-0012281-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
4017  P-0013096-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
4116  P-0013285-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
4329  P-0014119-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5

      startPosition referenceAllele variantAllele trinuc_context COSMIC96  \
943       112151184               A             G            AAT  A[T>C]T
963       112151184               A             G            AAT  A[T>C]T
976       112151184               A             G            AAT  A[T>C]T
1035      112151184               A             G            AAT  A[T>C]T
1130      112151184               A             G            AAT  A[T>C]T
2688      112151184               A             G            AAT  A[T>C]T
2971      112151184               A             G            AAT  A[T>C]T
3032      112151184               A             G            AAT  A[T>C]T
3162      112151184               A             G            AAT  A[T>C]T
3303      112151184               A             G            AAT  A[T>C]T
3323      112151184               A             G            AAT  A[T>C]T
3662      112151184               A             G            AAT  A[T>C]T
4017      112151184               A             G            AAT  A[T>C]T
4116      112151184               A             G            AAT  A[T>C]T
4329      112151184               A             G            AAT  A[T>C]T

     problem
943     None
963     None
976     None
1035    None
1130    None
2688    None
2971    None
3032    None
3162    None
3303    None
3323    None
3662    None
4017    None
4116    None
4329    None

In [66]:
print(final_df.columns)
print("Total recorded mutations:", len(final_df))
grouped = final_df[["sampleId", "mutationType", "referenceAllele"]].groupby("sampleId")#.count()
print("Total recorded patients:", len(grouped))
print("Average mutations recorded per sample:", np.mean(grouped.count()))
grouped.count()
# mut.head()

Index(['sampleId', 'patientId', 'gene', 'HGVSc', 'target splice', 'chr',
       'used_chr', 'startPosition', 'endPosition', 'referenceAllele',
       'variantAllele', 'proteinChange', 'mutationType', 'variantType',
       'ncbiBuild', 'trinuc_context', 'COSMIC96', 'problem'],
      dtype='object')
Total recorded mutations: 3509
Total recorded patients: 313
Average mutations recorded per sample: 11.210862619808307

                   mutationType  referenceAllele
sampleId
P-0000241-T01-IM3             6                6
P-0000493-T01-IM3             4                4
P-0000511-T01-IM3             3                3
P-0000526-T01-IM3             6                6
P-0000561-T01-IM3            18               18
...                         ...              ...
P-0014119-T01-IM5             5                5
P-0014168-T01-IM5             6                6
P-0014195-T01-IM6             6                6
P-0014296-T01-IM6             9                9
P-0014415-T01-IM6             3                3

[313 rows x 2 columns]

# Not Early Onset

In [67]:
import requests
import pandas as pd
import pandas as pd
from pyfaidx import Fasta # might need to do pip install first


base_url = "https://www.cbioportal.org/api"

# Choose study
profile = "crc_msk_2017_mutations"

# Choose sample ids the 35 IDs
sample_ids = IDs_Not_Early_list

payload = {"sampleIds": sample_ids}

headers = {
    "Accept": "application/json",
    "Content-Type": "application/json"
}

r = requests.post(
    f"{base_url}/molecular-profiles/{profile}/mutations/fetch",
    json=payload,
    headers=headers
)

mut = pd.DataFrame(r.json())

mut.to_csv("all_mutations_crc_msk2017_samples_Not_Early_Onset.csv", index=False)


# repeat if there are >1 studies, and merge into a single mut file

In [68]:
mut.head()

,uniqueSampleKey,uniquePatientKey,molecularProfileId,sampleId,patientId,entrezGeneId,studyId,center,mutationStatus,validationStatus,...,proteinChange,mutationType,ncbiBuild,variantType,keyword,chr,variantAllele,refseqMrnaId,proteinPosStart,proteinPosEnd
0,UC0wMDAwMTE5LVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMTE5OmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000119-T01-IM3,P-0000119,324,crc_msk_2017,MSKCC,NA,NA,...,E1097*,Nonsense_Mutation,GRCh37,SNP,APC truncating,5,T,NM_000038.5,1097,1097
1,UC0wMDAwMTE5LVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMTE5OmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000119-T01-IM3,P-0000119,324,crc_msk_2017,MSKCC,NA,NA,...,T1438Yfs*35,Frame_Shift_Del,GRCh37,DEL,APC truncating,5,T,NM_000038.5,1438,1438
2,UC0wMDAwMTE5LVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMTE5OmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000119-T01-IM3,P-0000119,2044,crc_msk_2017,MSKCC,NA,NA,...,R37W,Missense_Mutation,GRCh37,SNP,EPHA5 R37 missense,4,A,NM_004439.5,37,37
3,UC0wMDAwMTE5LVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMTE5OmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000119-T01-IM3,P-0000119,3845,crc_msk_2017,MSKCC,NA,NA,...,A146T,Missense_Mutation,GRCh37,SNP,KRAS A146 missense,12,T,NM_033360.2,146,146
4,UC0wMDAwMTE5LVQwMS1JTTM6Y3JjX21za18yMDE3,UC0wMDAwMTE5OmNyY19tc2tfMjAxNw,crc_msk_2017_mutations,P-0000119-T01-IM3,P-0000119,4089,crc_msk_2017,MSKCC,NA,NA,...,P91L,Missense_Mutation,GRCh37,SNP,SMAD4 P91 missense,18,T,NM_005359.5,91,91

In [69]:
mut.shape

(6990, 27)

In [70]:
mut[["sampleId", "mutationStatus", "referenceAllele", "proteinChange", "mutationType",
      "variantType", "keyword", "chr", "variantAllele"]].head()

,sampleId,mutationStatus,referenceAllele,proteinChange,mutationType,variantType,keyword,chr,variantAllele
0,P-0000119-T01-IM3,NA,G,E1097*,Nonsense_Mutation,SNP,APC truncating,5,T
1,P-0000119-T01-IM3,NA,AC,T1438Yfs*35,Frame_Shift_Del,DEL,APC truncating,5,T
2,P-0000119-T01-IM3,NA,G,R37W,Missense_Mutation,SNP,EPHA5 R37 missense,4,A
3,P-0000119-T01-IM3,NA,C,A146T,Missense_Mutation,SNP,KRAS A146 missense,12,T
4,P-0000119-T01-IM3,NA,C,P91L,Missense_Mutation,SNP,SMAD4 P91 missense,18,T

In [71]:
import numpy as np
print(mut.columns)
print("Total recorded mutations:", len(mut))
grouped = mut[["sampleId", "mutationType", "referenceAllele"]].groupby("sampleId")#.count()
print("Total recorded patients:", len(grouped))
print("Average mutations recorded per sample:", np.mean(grouped.count()))
grouped.count()
# mut.head()

Index(['uniqueSampleKey', 'uniquePatientKey', 'molecularProfileId', 'sampleId',
       'patientId', 'entrezGeneId', 'studyId', 'center', 'mutationStatus',
       'validationStatus', 'tumorAltCount', 'tumorRefCount', 'normalAltCount',
       'normalRefCount', 'startPosition', 'endPosition', 'referenceAllele',
       'proteinChange', 'mutationType', 'ncbiBuild', 'variantType', 'keyword',
       'chr', 'variantAllele', 'refseqMrnaId', 'proteinPosStart',
       'proteinPosEnd'],
      dtype='object')
Total recorded mutations: 6990
Total recorded patients: 554
Average mutations recorded per sample: 12.617328519855596

                   mutationType  referenceAllele
sampleId
P-0000119-T01-IM3             9                9
P-0000520-T01-IM3             5                5
P-0000552-T01-IM3             6                6
P-0000625-T01-IM3             9                9
P-0000635-T01-IM3             5                5
...                         ...              ...
P-0014116-T01-IM5            12               12
P-0014133-T01-IM5             6                6
P-0014182-T01-IM6             9                9
P-0014190-T01-IM6            11               11
P-0014252-T01-IM6             4                4

[554 rows x 2 columns]

In [72]:
import pandas as pd
from pyfaidx import Fasta

# -----------------------------
# Inputs
# -----------------------------
mut = pd.read_csv("all_mutations_crc_msk2017_samples_Not_Early_Onset.csv")

# Change this path if needed
fasta_path = "data/hg19.fa"
ref = Fasta(fasta_path)

# -----------------------------
# Basic cleanup / added columns
# -----------------------------
mut = mut.copy()

# cBioPortal export uses 'keyword' as gene symbol here
mut["gene"] = mut["keyword"]

# HGVSc is not present in this export
mut["HGVSc"] = pd.NA

# Mark the specific target splice-creating mutation:
# chr5:112151184 A>G
mut["target splice"] = (
    mut["chr"].astype(str).str.replace(r"\.0$", "", regex=True).isin(["5", "chr5"]) &
    pd.to_numeric(mut["startPosition"], errors="coerce").eq(112151184) &
    mut["referenceAllele"].astype(str).str.upper().eq("A") &
    mut["variantAllele"].astype(str).str.upper().eq("G")
).astype(int)

# -----------------------------
# Keep all single-base substitutions
# This includes splice SNVs and splice-creating SNVs
# -----------------------------
is_sbs = (
    mut["referenceAllele"].astype(str).str.len().eq(1) &
    mut["variantAllele"].astype(str).str.len().eq(1) &
    mut["referenceAllele"].astype(str).str.upper().isin(list("ACGT")) &
    mut["variantAllele"].astype(str).str.upper().isin(list("ACGT"))
)

snv = mut.loc[is_sbs].copy()

# -----------------------------
# Helpers for COSMIC96 assignment
# -----------------------------
comp = str.maketrans("ACGT", "TGCA")

# -----------------------------
# Annotate trinucleotide context and COSMIC96
# -----------------------------
contexts = []
classes = []
problems = []
used_chrs = []

for _, row in snv.iterrows():
    try:
        context, used_chr = get_context_pyfaidx(ref, row["chr"], row["startPosition"])
        ref_base = str(row["referenceAllele"]).upper()
        alt_base = str(row["variantAllele"]).upper()

        cosmic = to_cosmic96(context, ref_base, alt_base)

        contexts.append(context)
        classes.append(cosmic)
        used_chrs.append(used_chr)

        if context is None:
            problems.append("Could not extract 3bp context")
        elif cosmic is None:
            problems.append(
                f"Reference allele mismatch: FASTA middle base={context[1]}, mutation ref={ref_base}"
            )
        else:
            problems.append(None)

    except Exception as e:
        contexts.append(None)
        classes.append(None)
        used_chrs.append(None)
        problems.append(str(e))

snv["used_chr"] = used_chrs
snv["trinuc_context"] = contexts
snv["COSMIC96"] = classes
snv["problem"] = problems

# -----------------------------
# Build final dataframe
# -----------------------------
final_df = snv[[
    "sampleId",
    "patientId",
    "gene",
    "HGVSc",
    "target splice",
    "chr",
    "used_chr",
    "startPosition",
    "endPosition",
    "referenceAllele",
    "variantAllele",
    "proteinChange",
    "mutationType",
    "variantType",
    "ncbiBuild",
    "trinuc_context",
    "COSMIC96",
    "problem"
]].copy()

# -----------------------------
# Save outputs
# -----------------------------
final_df.to_csv("all_mutations_crc_msk2017_samples_Not_Early_Onset_cosmic96.csv", index=False)

counts = final_df["COSMIC96"].value_counts(dropna=True).sort_index()
counts.to_csv("Not_Early_Onset_cosmic96_counts.csv", header=["count"])

# -----------------------------
# Checks
# -----------------------------
print(final_df.head(20))

print("\nTarget splice rows:")
print(
    final_df.loc[final_df["target splice"] == 1, [
        "sampleId",
        "gene",
        "proteinChange",
        "mutationType",
        "chr",
        "startPosition",
        "referenceAllele",
        "variantAllele",
        "trinuc_context",
        "COSMIC96",
        "problem"
    ]]
)

             sampleId  patientId                   gene HGVSc  target splice  \
0   P-0000119-T01-IM3  P-0000119         APC truncating  <NA>              0
2   P-0000119-T01-IM3  P-0000119     EPHA5 R37 missense  <NA>              0
3   P-0000119-T01-IM3  P-0000119     KRAS A146 missense  <NA>              0
4   P-0000119-T01-IM3  P-0000119     SMAD4 P91 missense  <NA>              0
6   P-0000119-T01-IM3  P-0000119    HNF1A V617 missense  <NA>              0
7   P-0000119-T01-IM3  P-0000119    STAG2 L503 missense  <NA>              0
8   P-0000119-T01-IM3  P-0000119   KMT2C G2346 missense  <NA>              0
10  P-0000520-T01-IM3  P-0000520         APC truncating  <NA>              0
11  P-0000520-T01-IM3  P-0000520      KDR V514 missense  <NA>              0
12  P-0000520-T01-IM3  P-0000520  PIK3CA H1047 missense  <NA>              0
13  P-0000520-T01-IM3  P-0000520        SOX9 truncating  <NA>              0
14  P-0000552-T01-IM3  P-0000552         APC truncating  <NA>              0
15  P-0000552-T01-IM3  P-0000552     ATR K1595 missense  <NA>              0
16  P-0000552-T01-IM3  P-0000552     SMAD4 W99 missense  <NA>              0
17  P-0000552-T01-IM3  P-0000552      NRAS Q61 missense  <NA>              0
18  P-0000552-T01-IM3  P-0000552     TP53 S127 missense  <NA>              0
19  P-0000552-T01-IM3  P-0000552    IKZF1 V271 missense  <NA>              0
20  P-0000625-T01-IM3  P-0000625       ALK R28 missense  <NA>              0
21  P-0000625-T01-IM3  P-0000625         APC truncating  <NA>              0
22  P-0000625-T01-IM3  P-0000625      APC G637 missense  <NA>              0

    chr used_chr  startPosition  endPosition referenceAllele variantAllele  \
0     5     chr5      112174580    112174580               G             T
2     4     chr4       66535352     66535352               G             A
3    12    chr12       25378562     25378562               C             T
4    18    chr18       48575078     48575078               C             T
6    12    chr12      121438948    121438948               G             A
7    23     None      123195164    123195164               C             G
8     7     chr7      151877909    151877909               C             G
10    5     chr5      112174096    112174096               C             A
11    4     chr4       55972104     55972104               C             T
12    3     chr3      178952085    178952085               A             G
13   17    chr17       70120232     70120232               C             T
14    5     chr5      112175303    112175303               C             T
15    3     chr3      142231170    142231170               T             A
16   18    chr18       48575103     48575103               G             T
17    1     chr1      115256529    115256529               T             A
18   17    chr17        7578550      7578550               G             A
19    7     chr7       50459522     50459522               G             A
20    2     chr2       30143444     30143444               G             A
21    5     chr5      112137048    112137048               G             T
22    5     chr5      112170813    112170813               G             A

   proteinChange       mutationType variantType ncbiBuild trinuc_context  \
0         E1097*  Nonsense_Mutation         SNP    GRCh37            GGA
2           R37W  Missense_Mutation         SNP    GRCh37            CGT
3          A146T  Missense_Mutation         SNP    GRCh37            GCT
4           P91L  Missense_Mutation         SNP    GRCh37            CCT
6          V617I  Missense_Mutation         SNP    GRCh37            CGT
7          L503V  Missense_Mutation         SNP    GRCh37           None
8         G2346R  Missense_Mutation         SNP    GRCh37            CCT
10         Y935*  Nonsense_Mutation         SNP    GRCh37            ACA
11         V514I  Missense_Mutation         SNP    GRCh37            ACA
12        H1047R  Missense_Mutation         SNP    GRCh37            CAT
13         Q412*  Nonsense_Mutation         SNP    GRCh37            GCA
14        Q1338*  Nonsense_Mutation         SNP    GRCh37            GCA
15        K1595I  Missense_Mutation         SNP    GRCh37            TTT
16          W99C  Missense_Mutation         SNP    GRCh37            GGA
17          Q61L  Missense_Mutation         SNP    GRCh37            TTG
18         S127F  Missense_Mutation         SNP    GRCh37            GGA
19         V271I  Missense_Mutation         SNP    GRCh37            CGT
20          R28C  Missense_Mutation         SNP    GRCh37            CGC
21         E268*  Nonsense_Mutation         SNP    GRCh37            AGA
22         G637R  Missense_Mutation         SNP    GRCh37            TGG

   COSMIC96                             problem
0   T[C>A]C                                None
2   A[C>T]G                                None
3   G[C>T]T                                None
4   C[C>T]T                                None
6   A[C>T]G                                None
7      None  'Chromosome 23 not found in FASTA'
8   C[C>G]T                                None
10  A[C>A]A                                None
11  A[C>T]A                                None
12  A[T>C]G                                None
13  G[C>T]A                                None
14  G[C>T]A                                None
15  T[T>A]T                                None
16  T[C>A]C                                None
17  T[T>A]G                                None
18  T[C>T]C                                None
19  A[C>T]G                                None
20  G[C>T]G                                None
21  T[C>A]T                                None
22  C[C>T]A                                None

Target splice rows:
               sampleId            gene proteinChange     mutationType  chr  \
1371  P-0004502-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
1455  P-0004736-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2149  P-0005446-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2212  P-0005502-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2343  P-0005569-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2417  P-0005941-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
2452  P-0006136-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3077  P-0006735-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3156  P-0006763-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3220  P-0006864-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3616  P-0006978-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
3825  P-0007315-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
4599  P-0008584-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
5117  P-0010134-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
5755  P-0011110-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
5882  P-0011296-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
6198  P-0011455-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
6537  P-0013087-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
6652  P-0013354-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5
6845  P-0013820-T01-IM5  APC truncating    G279Ffs*10  Frame_Shift_Ins    5

      startPosition referenceAllele variantAllele trinuc_context COSMIC96  \
1371      112151184               A             G            AAT  A[T>C]T
1455      112151184               A             G            AAT  A[T>C]T
2149      112151184               A             G            AAT  A[T>C]T
2212      112151184               A             G            AAT  A[T>C]T
2343      112151184               A             G            AAT  A[T>C]T
2417      112151184               A             G            AAT  A[T>C]T
2452      112151184               A             G            AAT  A[T>C]T
3077      112151184               A             G            AAT  A[T>C]T
3156      112151184               A             G            AAT  A[T>C]T
3220      112151184               A             G            AAT  A[T>C]T
3616      112151184               A             G            AAT  A[T>C]T
3825      112151184               A             G            AAT  A[T>C]T
4599      112151184               A             G            AAT  A[T>C]T
5117      112151184               A             G            AAT  A[T>C]T
5755      112151184               A             G            AAT  A[T>C]T
5882      112151184               A             G            AAT  A[T>C]T
6198      112151184               A             G            AAT  A[T>C]T
6537      112151184               A             G            AAT  A[T>C]T
6652      112151184               A             G            AAT  A[T>C]T
6845      112151184               A             G            AAT  A[T>C]T

     problem
1371    None
1455    None
2149    None
2212    None
2343    None
2417    None
2452    None
3077    None
3156    None
3220    None
3616    None
3825    None
4599    None
5117    None
5755    None
5882    None
6198    None
6537    None
6652    None
6845    None

In [73]:
print(final_df.columns)
print("Total recorded mutations:", len(final_df))
grouped = final_df[["sampleId", "mutationType", "referenceAllele"]].groupby("sampleId")#.count()
print("Total recorded patients:", len(grouped))
print("Average mutations recorded per sample:", np.mean(grouped.count()))
grouped.count()
# mut.head()

Index(['sampleId', 'patientId', 'gene', 'HGVSc', 'target splice', 'chr',
       'used_chr', 'startPosition', 'endPosition', 'referenceAllele',
       'variantAllele', 'proteinChange', 'mutationType', 'variantType',
       'ncbiBuild', 'trinuc_context', 'COSMIC96', 'problem'],
      dtype='object')
Total recorded mutations: 5761
Total recorded patients: 552
Average mutations recorded per sample: 10.43659420289855

                   mutationType  referenceAllele
sampleId
P-0000119-T01-IM3             7                7
P-0000520-T01-IM3             4                4
P-0000552-T01-IM3             6                6
P-0000625-T01-IM3             8                8
P-0000635-T01-IM3             5                5
...                         ...              ...
P-0014116-T01-IM5            11               11
P-0014133-T01-IM5             5                5
P-0014182-T01-IM6             8                8
P-0014190-T01-IM6             8                8
P-0014252-T01-IM6             2                2

[552 rows x 2 columns]