In [1]:
import pandas as pd
import numpy as np

<center> Read CSV file</center>

In [2]:
# NEED TO CHANGE TO SPECIFIED LOC 
df = pd.read_csv(r"C:\Users\abbi_\venv1\RSCAM\rscam-g6\data\tcga_data2.csv", sep = "\t", low_memory=False)
df.head()

,Gene,Study of Origin,Sample ID,Cancer Type,Cancer Type Detailed,Protein Change,Annotation,Custom Driver,Custom Driver Tiers,Functional Impact,...,Tumor Type,Used in Genomic Analysis,Vascular invasion indicator,Vessel Invasion,Vial number,Patient's Vital Status,Patient Weight,WGD,Winter Hypoxia Score,Year of Diagnosis
0,APC,"Colorectal Adenocarcinoma (TCGA, Firehose Legacy)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NO,NaN,A,NaN,NaN,NaN,NaN,NaN
1,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Colon Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,APC,"Colorectal Adenocarcinoma (TCGA, Nature 2012)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-EI-6917-01,Colorectal Cancer,Rectal Adenocarcinoma,A3T,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Rectal Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,80.0,NaN,30.0,NaN
4,APC,"Colorectal Adenocarcinoma (DFCI, Cell Reports ...",coadread_dfci_2016_3235,Colorectal Cancer,Colorectal Adenocarcinoma,L23I,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.loc[:, df.columns.str.lower().str.contains("age")].head()

,Diagnosis Age,Age at derivation,Age at Diagnosis,Age At Diagnosis,Age at Metastases,Age at Which Sequencing was Reported (Days),Age at Which Sequencing was Reported (Years),American Joint Committee on Cancer Metastasis Stage Code,Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code,Neoplasm Disease Stage American Joint Committee on Cancer Code,...,American Joint Committee on Cancer Tumor Stage Code.1,Post-Operative Therapy With Targeted Agents,Pre-Therapy With Targeted Agents,Sample coverage,Stage,Stage At Diagnosis,Stage Other,TNM Stage,Tumor Stage,Tumor Stage 2009
0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,M0,N0,Stage IIB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STAGE IIB,...,T4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage IIB
3,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STAGE IIIA,...,T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I,NaN

<center> Find columns that contain diagnosis age (or similar) and combine. Choose first non-null age.</center>

REF https://shecancode.io/filter-a-pandas-dataframe-by-a-partial-string-or-pattern-in-8-ways/#:~:text=Filter%20rows%20that%20match%20a%20given%20String%20in%20a%20column&text=We%20will%20use%20the%20Series,in%20the%20isin()%20function.

In [4]:
mask = (df.columns.str.lower().str.contains("age") 
        & df.columns.str.lower().str.contains("diagnos")
        & ~df.columns.str.lower().str.contains("stage")
       )

# df.loc[:,mask].head()
cols = df.columns[mask]
# Not sure if bfill is the best choice here
df["Diagnosis Age"] = df.loc[:,cols].bfill(axis = 1).iloc[:,0]
df.drop(columns=cols).copy()
df.head()

,Gene,Study of Origin,Sample ID,Cancer Type,Cancer Type Detailed,Protein Change,Annotation,Custom Driver,Custom Driver Tiers,Functional Impact,...,Tumor Type,Used in Genomic Analysis,Vascular invasion indicator,Vessel Invasion,Vial number,Patient's Vital Status,Patient Weight,WGD,Winter Hypoxia Score,Year of Diagnosis
0,APC,"Colorectal Adenocarcinoma (TCGA, Firehose Legacy)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NO,NaN,A,NaN,NaN,NaN,NaN,NaN
1,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Colon Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,APC,"Colorectal Adenocarcinoma (TCGA, Nature 2012)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-EI-6917-01,Colorectal Cancer,Rectal Adenocarcinoma,A3T,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Rectal Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,80.0,NaN,30.0,NaN
4,APC,"Colorectal Adenocarcinoma (DFCI, Cell Reports ...",coadread_dfci_2016_3235,Colorectal Cancer,Colorectal Adenocarcinoma,L23I,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<center>Create new Dataframe only with essential information</center>

In [5]:
for col in df.columns:
    df.columns = df.columns.str.strip()

In [20]:
note_cols = ["Gene", "Sample ID", "Cancer Type Detailed", "Mutation Type", "Variant Type", "HGVSc", "MS", 
        "Protein Change", "Functional Impact", "Diagnosis Age"]
rel_df = df[note_cols]
rel_df.head()

,Gene,Sample ID,Cancer Type Detailed,Mutation Type,Variant Type,HGVSc,MS,Protein Change,Functional Impact,Diagnosis Age
0,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,Somatic,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,46.0
1,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,.,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,46.0
2,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,Somatic,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,NaN
3,APC,TCGA-EI-6917-01,Rectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.7G>A,.,A3T,MutationAssessor: NA;SIFT: impact: deleterious...,33.0
4,APC,coadread_dfci_2016_3235,Colorectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.67C>A,NaN,L23I,MutationAssessor: NA;SIFT: impact: deleterious...,86.0

<center>Remove entries with no diagnosis age attached</center>

In [21]:
removed_rows = rel_df.dropna(subset =["Diagnosis Age"], axis = 0)
removed_rows.head()

,Gene,Sample ID,Cancer Type Detailed,Mutation Type,Variant Type,HGVSc,MS,Protein Change,Functional Impact,Diagnosis Age
0,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,Somatic,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,46.0
1,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,.,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,46.0
3,APC,TCGA-EI-6917-01,Rectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.7G>A,.,A3T,MutationAssessor: NA;SIFT: impact: deleterious...,33.0
4,APC,coadread_dfci_2016_3235,Colorectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.67C>A,NaN,L23I,MutationAssessor: NA;SIFT: impact: deleterious...,86.0
5,APC,coadread_dfci_2016_2367,Colorectal Adenocarcinoma,Nonsense_Mutation,SNP,ENST00000257430.4:c.70C>T,NaN,R24*,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,66.0

<center> Remove duplicate samples</center>

In [22]:
print(removed_rows.shape)

(4877, 10)

In [23]:
unique_samples = removed_rows["Sample ID"].unique()
print(unique_samples.shape)

(2638,)

In [24]:
cleaned_df = removed_rows.drop_duplicates(subset=["Sample ID"], keep='first')
cleaned_df.shape
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2638 entries, 0 to 6492
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Gene                  2638 non-null   object
 1   Sample ID             2638 non-null   object
 2   Cancer Type Detailed  2638 non-null   object
 3   Mutation Type         2638 non-null   object
 4   Variant Type          2638 non-null   object
 5   HGVSc                 2597 non-null   object
 6   MS                    569 non-null    object
 7   Protein Change        2638 non-null   object
 8   Functional Impact     2638 non-null   object
 9   Diagnosis Age         2638 non-null   float64
dtypes: float64(1), object(9)
memory usage: 226.7+ KB

In [25]:
cleaned_df.head()

,Gene,Sample ID,Cancer Type Detailed,Mutation Type,Variant Type,HGVSc,MS,Protein Change,Functional Impact,Diagnosis Age
0,APC,TCGA-AA-A010-01,Colon Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.5C>A,Somatic,A2D,MutationAssessor: NA;SIFT: impact: deleterious...,46.0
3,APC,TCGA-EI-6917-01,Rectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.7G>A,.,A3T,MutationAssessor: NA;SIFT: impact: deleterious...,33.0
4,APC,coadread_dfci_2016_3235,Colorectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.67C>A,NaN,L23I,MutationAssessor: NA;SIFT: impact: deleterious...,86.0
5,APC,coadread_dfci_2016_2367,Colorectal Adenocarcinoma,Nonsense_Mutation,SNP,ENST00000257430.4:c.70C>T,NaN,R24*,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,66.0
6,APC,P-0006759-T01-IM5,Colorectal Adenocarcinoma,Missense_Mutation,SNP,ENST00000257430.4:c.100C>T,NaN,L34F,MutationAssessor: NA;SIFT: impact: deleterious...,51.0

In [26]:
cleaned_df = cleaned_df.loc[cleaned_df["HGVSc"] == "ENST00000257430.4:c.835-8A>G"]
cleaned_df.shape

(32, 10)

<center> Add column for early onset</center>

In [27]:
cleaned_df = cleaned_df.copy()
cleaned_df["Early Onset"] = cleaned_df["Diagnosis Age"] <= 50
cleaned_df.head()

,Gene,Sample ID,Cancer Type Detailed,Mutation Type,Variant Type,HGVSc,MS,Protein Change,Functional Impact,Diagnosis Age,Early Onset
583,APC,P-0003365-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,45.0,True
584,APC,P-0003575-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,38.0,True
585,APC,P-0003710-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,42.0,True
587,APC,P-0004369-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,48.0,True
588,APC,P-0004502-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,72.0,False

<center> Locate rows where Early Onset = True</center>

In [30]:
early_onset = cleaned_df.copy()
early_onset = early_onset.loc[early_onset["Early Onset"] == True]
early_onset

,Gene,Sample ID,Cancer Type Detailed,Mutation Type,Variant Type,HGVSc,MS,Protein Change,Functional Impact,Diagnosis Age,Early Onset
583,APC,P-0003365-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,45.0,True
584,APC,P-0003575-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,38.0,True
585,APC,P-0003710-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,42.0,True
587,APC,P-0004369-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,48.0,True
600,APC,P-0007631-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,43.0,True
601,APC,P-0008534-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,37.0,True
603,APC,P-0009341-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,40.0,True
606,APC,P-0010364-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,49.0,True
607,APC,P-0010393-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,44.0,True
611,APC,P-0012281-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,35.0,True
613,APC,P-0013096-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,33.0,True
614,APC,P-0013285-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,39.0,True
615,APC,P-0013354-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,50.0,True
617,APC,P-0014119-T01-IM5,Colorectal Adenocarcinoma,Frame_Shift_Ins,SNP,ENST00000257430.4:c.835-8A>G,NaN,G279Ffs*10,MutationAssessor: NA;SIFT: NA;Polyphen-2: NA;A...,47.0,True

In [29]:
early_onset.shape

(14, 11)