In [35]:
import pandas as pd
import numpy as np

<center> Read CSV file</center>

In [36]:
# NEED TO CHANGE TO SPECIFIED LOC 
df = pd.read_csv(r"C:\Users\abbi_\venv1\RSCAM\rscam-g6\data\newdata.csv", low_memory=False)
df.head()

,Gene,Study of Origin,Sample ID,Cancer Type,Cancer Type Detailed,Protein Change,Annotation,Custom Driver,Custom Driver Tiers,Functional Impact,...,Tumor Type,Used in Genomic Analysis,Vascular invasion indicator,Vessel Invasion,Vial number,Patient's Vital Status,Patient Weight,WGD,Winter Hypoxia Score,Year of Diagnosis
0,APC,"Colorectal Adenocarcinoma (TCGA, Firehose Legacy)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NO,NaN,A,NaN,NaN,NaN,NaN,NaN
1,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Colon Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,APC,"Colorectal Adenocarcinoma (TCGA, Nature 2012)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-EI-6917-01,Colorectal Cancer,Rectal Adenocarcinoma,A3T,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Rectal Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,80.0,NaN,30.0,NaN
4,APC,"Colorectal Adenocarcinoma (DFCI, Cell Reports ...",coadread_dfci_2016_3235,Colorectal Cancer,Colorectal Adenocarcinoma,L23I,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df.loc[:, df.columns.str.lower().str.contains("age")].head()

,Diagnosis Age,Age at derivation,Age at Diagnosis,Age At Diagnosis,Age at Metastases,Age at Which Sequencing was Reported (Days),Age at Which Sequencing was Reported (Years),American Joint Committee on Cancer Metastasis Stage Code,Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code,Neoplasm Disease Stage American Joint Committee on Cancer Code,...,American Joint Committee on Cancer Tumor Stage Code.1,Post-Operative Therapy With Targeted Agents,Pre-Therapy With Targeted Agents,Sample coverage,Stage,Stage At Diagnosis,Stage Other,TNM Stage,Tumor Stage,Tumor Stage 2009
0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,M0,N0,Stage IIB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STAGE IIB,...,T4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stage IIB
3,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STAGE IIIA,...,T3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I,NaN

<center> Find columns that contain diagnosis age (or similar) and combine. Choose first non-null age.</center>

REF https://shecancode.io/filter-a-pandas-dataframe-by-a-partial-string-or-pattern-in-8-ways/#:~:text=Filter%20rows%20that%20match%20a%20given%20String%20in%20a%20column&text=We%20will%20use%20the%20Series,in%20the%20isin()%20function.

In [38]:
mask = (df.columns.str.lower().str.contains("age") 
        & df.columns.str.lower().str.contains("diagnos")
        & ~df.columns.str.lower().str.contains("stage")
       )

df.loc[:,mask].head()
cols = df.columns[mask]
# Not sure if bfill is the best choice here
df["Diagnosis Age"] = df.loc[:,cols].bfill(axis = 1).iloc[:,0]
df.drop(columns=cols).copy()
df.head()

,Gene,Study of Origin,Sample ID,Cancer Type,Cancer Type Detailed,Protein Change,Annotation,Custom Driver,Custom Driver Tiers,Functional Impact,...,Tumor Type,Used in Genomic Analysis,Vascular invasion indicator,Vessel Invasion,Vial number,Patient's Vital Status,Patient Weight,WGD,Winter Hypoxia Score,Year of Diagnosis
0,APC,"Colorectal Adenocarcinoma (TCGA, Firehose Legacy)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NO,NaN,A,NaN,NaN,NaN,NaN,NaN
1,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Colon Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,APC,"Colorectal Adenocarcinoma (TCGA, Nature 2012)",TCGA-AA-A010-01,Colorectal Cancer,Colon Adenocarcinoma,A2D,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,APC,"Colorectal Adenocarcinoma (TCGA, PanCancer Atlas)",TCGA-EI-6917-01,Colorectal Cancer,Rectal Adenocarcinoma,A3T,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,Rectal Adenocarcinoma,NaN,NaN,NaN,NaN,NaN,80.0,NaN,30.0,NaN
4,APC,"Colorectal Adenocarcinoma (DFCI, Cell Reports ...",coadread_dfci_2016_3235,Colorectal Cancer,Colorectal Adenocarcinoma,L23I,"OncoKB: Unknown, level NA, resistance NA;reVUE...",NaN,NaN,MutationAssessor: NA;SIFT: impact: deleterious...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<center>Create new Dataframe only with essential information</center>

In [39]:
for col in df.columns:
    df.columns = df.columns.str.strip()

In [41]:
rel_df = df[["Sample ID", "Diagnosis Age"]]
rel_df.head()

                 Sample ID  Diagnosis Age
0          TCGA-AA-A010-01           46.0
1          TCGA-AA-A010-01           46.0
2          TCGA-AA-A010-01            NaN
3          TCGA-EI-6917-01           33.0
4  coadread_dfci_2016_3235           86.0

<center>Remove entries with no diagnosis age attached</center>

In [42]:
removed_rows = rel_df.dropna(subset =["Diagnosis Age"], axis = 0)
removed_rows.head()

                 Sample ID  Diagnosis Age
0          TCGA-AA-A010-01           46.0
1          TCGA-AA-A010-01           46.0
3          TCGA-EI-6917-01           33.0
4  coadread_dfci_2016_3235           86.0
5  coadread_dfci_2016_2367           66.0

<center> Remove duplicate samples</center>

In [43]:
print(removed_rows.shape)

(4877, 2)

In [44]:
unique_samples = removed_rows["Sample ID"].unique()
print(unique_samples.shape)

(2638,)

In [45]:
cleaned_df = removed_rows.drop_duplicates(subset=["Sample ID"], keep='first')
cleaned_df.shape

(2638, 2)

In [46]:
cleaned_df.head()

                 Sample ID  Diagnosis Age
0          TCGA-AA-A010-01           46.0
3          TCGA-EI-6917-01           33.0
4  coadread_dfci_2016_3235           86.0
5  coadread_dfci_2016_2367           66.0
6        P-0006759-T01-IM5           51.0

<center> Add column for early onset</center>

In [47]:
cleaned_df = cleaned_df.copy()
cleaned_df["Early Onset"] = cleaned_df["Diagnosis Age"] <= 40
cleaned_df.head()

                 Sample ID  Diagnosis Age  Early Onset
0          TCGA-AA-A010-01           46.0        False
3          TCGA-EI-6917-01           33.0         True
4  coadread_dfci_2016_3235           86.0        False
5  coadread_dfci_2016_2367           66.0        False
6        P-0006759-T01-IM5           51.0        False

<center> Locate rows where Early Onset = True</center>

In [48]:
early_onset = cleaned_df.copy()
early_onset.loc[early_onset["Early Onset"] == True]

              Sample ID  Diagnosis Age  Early Onset
3       TCGA-EI-6917-01           33.0         True
17    P-0006365-T01-IM5           30.0         True
26      TCGA-AG-A002-01           35.0         True
51    P-0006202-T01-IM5           25.0         True
60    P-0047886-T01-IM6           32.0         True
...                 ...            ...          ...
5320          CRC888_NT           37.0         True
5392  P-0010112-T01-IM5           34.0         True
5465  P-0013876-T01-IM5           36.0         True
5527  P-0013227-T01-IM5           28.0         True
5621          CRC807_NT           38.0         True

[173 rows x 3 columns]

In [ ]:
# new_df = pd.read_csv(r"C:\Users\abbi_\venv1\RSCAM\rscam-g6\data\tcga_data.csv")